app/routes.php
<?php
Event::listen('illuminate.query', function ($sql) {
    // var_dump($sql);
});

Route::get('/current_environment', array(
    'as' => 'test.environment',
    'uses' => 'TestController@environment'
));

Route::get('auth/logout', array(
    'as' => 'auth.logout',
    'uses' => 'AuthController@getLogout'
));
Route::get('auth/login', array(
    'as' => 'auth.login',
    'uses' => 'AuthController@getLogin'
));
Route::post('auth/login', array(
    'as' => 'auth.login.post',
    'uses' => 'AuthController@postLogin'
));

Route::group(array(
    'prefix' => 'project_importer'
        ), function () {
    Route::get('/', array(
        'as' => 'project_importer.index',
        'uses' => 'ProjectImporterController@index'
    ));
    Route::get('/sync_data_from_erp', array(
        'as' => 'project_importer.import_to_db',
        'uses' => 'ProjectImporterController@sync_data_from_erp'
    ));
});

Route::group(array('before' => 'auth.apps'), function () {
    Route::any('/', 'DashboardController@index');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('user', 'UserController');
    Route::resource('userlevel', 'UserLevelController');
    Route::resource('department', 'DepartmentController');
    Route::resource('unit', 'UnitController');
    Route::resource('pic', 'PicController');
    Route::resource('resource', 'ResourceController');
    Route::resource('resource_group', 'ResourceGroupController');
    Route::resource('resource_planner', 'ResourcePlannerController');
    Route::resource('resource_monitor', 'ResourceMonitorController');
    Route::resource('resource_manager', 'ResourceManagerController');
    Route::resource('setting', 'SettingController');
    Route::resource('alert_setting', 'AlertSettingsController');
    Route::resource('email_recipient', 'SettingController');
    Route::resource('helpdesk', 'HelpDeskController');
    Route::resource('helpdesk_request', 'HelpDeskRequestController');
    Route::resource('processes', 'ProjectProcessController');
    Route::resource('process_group', 'ProcessGroupController');
    Route::resource('template_master_plan', 'TemplateMasterPlanController');
    Route::resource('template_mfg_process', 'TemplateMfgProcessController');
    Route::resource('work_time_template', 'ResourceWorkTimeTemplateController');
    Route::resource('menu', 'MenuController');
    Route::resource('exception_days', 'ExceptionDaysController');
    // Route::resource('issue_management', 'IssueManagementsController');
    Route::resource('document', 'DocumentManagementsController');

    // Route::group(array('prefix' => 'issue_management'), function () {
    //     Route::get('/sel', array(
    //         'as' => 'issue_management.select',
    //         'uses' => 'iqi@select_project'
    //     ));

    // });

    Route::group(array(
        'prefix' => 'template_master_plan/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_master_plan_detail.index',
            'uses' => 'TemplateMasterPlanDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_master_plan_detail.create',
            'uses' => 'TemplateMasterPlanDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_master_plan_detail.create.child',
            'uses' => 'TemplateMasterPlanDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_master_plan_detail.store',
            'uses' => 'TemplateMasterPlanDetailController@store'
        ));
        Route::post('/{header_id}/{detail_id}/store', array(
            'as' => 'template_master_plan_detail.store.child',
            'uses' => 'TemplateMasterPlanDetailController@store_child'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_master_plan_detail.edit',
            'uses' => 'TemplateMasterPlanDetailController@edit'
        ));
        Route::post('/{detail_id}/update', array(
            'as' => 'template_master_plan_detail.update',
            'uses' => 'TemplateMasterPlanDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_master_plan_detail.destroy',
            'uses' => 'TemplateMasterPlanDetailController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'template_mfg_process/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_mfg_process_detail.index',
            'uses' => 'TemplateMfgProcessDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_mfg_process_detail.create',
            'uses' => 'TemplateMfgProcessDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_mfg_process_detail.create.child',
            'uses' => 'TemplateMfgProcessDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_mfg_process_detail.store',
            'uses' => 'TemplateMfgProcessDetailController@store'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_mfg_process_detail.edit',
            'uses' => 'TemplateMfgProcessDetailController@edit'
        ));
        Route::put('/{detail_id}/update', array(
            'as' => 'template_mfg_process_detail.update',
            'uses' => 'TemplateMfgProcessDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_mfg_process_detail.destroy',
            'uses' => 'TemplateMfgProcessDetailController@destroy'
        ));
    });

    Route::get('template_mfg_process/excel/import', array(
        'as' => 'template_mfg_process.excel.import',
        'uses' => 'TemplateMfgProcessController@import_excel'
    ));

    Route::post('template_mfg_process/excel/do_import', array(
        'as' => 'template_mfg_process.excel.do_import',
        'uses' => 'TemplateMfgProcessController@do_import_excel'
    ));

    Route::get('/', array(
        'as' => 'dashboard.index',
        'uses' => 'DashboardController@index'
    ));

    Route::get('resource/{id}/set_offline', array(
        'as' => 'resource_manager.set_offline',
        'uses' => 'ResourceManagerController@offline'
    ));

    Route::get('resource_planner/{year}/update', array(
        'as' => 'resource_planner.update.by_year',
        'uses' => 'ResourcePlannerController@create'
    ));

    Route::get('resource_planner/{year}/index', array(
        'as' => 'resource_planner.by_year',
        'uses' => 'ResourcePlannerController@index'
    ));

    Route::get('resource_planner/{resourceid}/{month}/{year}/work_plan', array(
        'as' => 'resource_planner.work_plan',
        'uses' => 'ResourcePlannerController@work_plan_per_month'
    ));

    Route::post('resource_planner/update_work_time_plan', array(
        'as' => 'resource_planner.update_work_time_plan',
        'uses' => 'ResourcePlannerController@update_work_time_plan'
    ));

    Route::post('helpdesk/{requestid}/add_note', array(
        'as' => 'helpdesk.add_note',
        'uses' => 'HelpDeskController@add_note'
    ));

    Route::post('helpdesk_request/{requestid}/update_status', array(
        'as' => 'helpdesk_request.update_status',
        'uses' => 'HelpDeskRequestController@update_status'
    ));

    Route::post('helpdesk_request/{requestid}/add_note', array(
        'as' => 'helpdesk_request.add_note',
        'uses' => 'HelpDeskRequestController@add_note'
    ));

    Route::group(array(
        'prefix' => 'resource_specification'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_spec.index',
            'uses' => 'ResourceSpecificationController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_spec.create',
            'uses' => 'ResourceSpecificationController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_spec.store',
            'uses' => 'ResourceSpecificationController@store'
        ));
        Route::get('/{resourceid}/{id}/show', array(
            'as' => 'resource_spec.show',
            'uses' => 'ResourceSpecificationController@show'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_spec.edit',
            'uses' => 'ResourceSpecificationController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_spec.update',
            'uses' => 'ResourceSpecificationController@update'
        ));
        Route::post('/{resourceid}/{id}/destroy', array(
            'as' => 'resource_spec.destroy',
            'uses' => 'ResourceSpecificationController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'resource_work_time'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_work_time.index',
            'uses' => 'ResourceWorkTimeController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_work_time.create',
            'uses' => 'ResourceWorkTimeController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_work_time.store',
            'uses' => 'ResourceWorkTimeController@store'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_work_time.edit',
            'uses' => 'ResourceWorkTimeController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_work_time.update',

app/models/Department.php
<?php

class Department extends Eloquent
{

    protected $table = 'master_department';

    public static function getSingle($id)
    {
        return self::find($id);
    }

    public static function getName($id)
    {
        $dept = self::find($id);

        return $dept->name;
    }

    public static function getAll()
    {
        return self::all();
    }
}

app/controllers/DepartmentController.php
<?php
use UserInformation;
use Department;
use Unit;
// // use Auth, BaseController, Form, Input, Redirect, Sentry, View, Notification;

class DepartmentController extends BaseController
{

    public function __construct()
    {
        View::composer(Config::get('app.theme').'._layouts.master', function ($view)
        {
            $view->with('parent_active', 'user_management');
            $view->with('child_active', 'department');
        });
    }

    public function index()
    {
        $view = View::make(Config::get('app.theme').'.department.list');
        $view->with('page_title', 'Department Management');
        $view->with('sub_title', 'Manage company department');
        $view->with('theme', Config::get('app.theme'));
        $view->with('departments', Department::getAll());

        return $view;
    }

    public function create()
    {
        $view = View::make(Config::get('app.theme').'.department.create');
        $view->with('page_title', 'Department Management');
        $view->with('sub_title', 'Create new department');
        $view->with('theme', Config::get('app.theme'));

        return $view;
    }

    public function store()
    {
        $department = new Department;
        $department->code = Input::get('code');
        $department->name = Input::get('deptname');
        $department->desc = Input::get('desc');

        if($department->save())
            Notification::success('New department data was saved.');

        return Redirect::route('department.index');
    }

    public function edit($id)
    {
        $view = View::make(Config::get('app.theme').'.department.edit');
        $view->with('page_title', 'Department Management');
        $view->with('sub_title', 'Edit department data');
        $view->with('theme', Config::get('app.theme'));
        $view->with('department', Department::find($id));

        return $view;
    }

    public function update($id)
    {
        $department = Department::find($id);
        $department->code = Input::get('code');
        $department->name = Input::get('deptname');
        $department->desc = Input::get('desc');

        if($department->save())
            Notification::success('Department data changes was saved.');

        return Redirect::route('department.index');
    }

    public function destroy($id)
    {
        $department = Department::find($id);
        $department->delete();

        return Redirect::route('department.index');
    }
}

app/views/default/department/create.blade.php
@extends($theme . '._layouts.master')
 
@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="wrapper">
    
    <!-- Note -->
    {{ Notification::showAll() }}
    
    <!-- Validation form -->
    {{ Form::open(array('route' => 'department.store', 'class' => 'form', 'id' => 'validate')) }}
    	<fieldset>
            <div class="widget">
                <div class="title">
                    <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/alert.png') }}}" alt="" class="titleIcon" />
                    <h6>Department</h6>
                </div>
                <div class="formRow">
                    <label>Code:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="code" id="code"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Name:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="deptname" id="deptname"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Description:</label>
                    <div class="formRight">
                        <textarea name="desc"></textarea>
                    </div><div class="clear"></div>
                </div>
                
            </div>
            <div class="formSubmit"><input type="hidden" name="formtype" value="informations" /><input type="submit" value="Create New Department" class="redB" /></div>
            <div class="clear"></div>
        </fieldset>
    {{ Form::close() }}        
    
</div>
@stop

app/views/default/department/edit.blade.php
@extends($theme . '._layouts.master')
 
@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="wrapper">
    
    <!-- Note -->
    {{ Notification::showAll() }}
    
    <!-- Validation form -->
    {{ Form::model($department, array('method' => 'put', 'class' => 'form', 'id' => 'validate', 'route' => array('department.update', $department->id))) }}
    	<fieldset>
            <div class="widget">
                <div class="title">
                    <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/alert.png') }}}" alt="" class="titleIcon" />
                    <h6>Department</h6>
                </div>
                <div class="formRow">
                    <label>Code:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="code" id="code" value="{{{ $department->code }}}"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Name:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="deptname" id="deptname" value="{{{ $department->name }}}"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Description:</label>
                    <div class="formRight">
                        <textarea name="desc">{{{ $department->desc }}}</textarea>
                    </div><div class="clear"></div>
                </div>
                
            </div>
            <div class="formSubmit"><input type="hidden" name="formtype" value="informations" /><input type="submit" value="Edit Department Data" class="redB" /></div>
            <div class="clear"></div>
        </fieldset>
    {{ Form::close() }}        
    
</div>
@stop

app/views/default/department/list.blade.php
@extends($theme . '._layouts.master')
 
@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="statsRow">
    <div class="wrapper">
    	<div class="controlB">
        	<ul>
                <li><a href="{{{ route('pic.index') }}}" title="Manage PIC data"><img src="<?php echo asset('assets/'.$theme.'/images/icons/control/32/administrative-docs.png') ?>" alt=""><span>PIC</span></a></li>
                <li><a href="{{{ route('unit.index') }}}" title="Manage units"><img src="<?php echo asset('assets/'.$theme.'/images/icons/control/32/order.png') ?>" alt=""><span>Units</span></a></li>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="line"></div>

<!-- Main content wrapper -->
<div class="wrapper">
    {{ Notification::showAll() }}
    
    <!-- Static table -->
    <div class="widget">
      <div class="title">
        <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/frames.png') }}}" alt="" class="titleIcon" />
        <h6>Department Lists</h6>
        <a href="{{{ route('department.create') }}}" title="Add New Department" class="button greenB" style="margin: 4px; float: right;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/plus.png') }}}" alt="Add User" class="icon" style="margin-top: 5px; margin-left: 5px;"><span>Add New Department</span></a>
      </div>
        <table cellpadding="0" cellspacing="0" width="100%" class="sTable">
            <thead>
                <tr>
                    <td>Code</td>
                    <td>Name</td>
                    <td width="11%">Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($departments as $dept)
                <tr>
                    <td>{{{ $dept->code }}}</td>
                    <td align="center">{{{ $dept->name }}}</td>
                    <td align="center">
                        <a href="{{{ route('department.edit', $dept->id) }}}" title="Edit" class="smallButton" style="margin: 5px;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/pencil.png') }}}" alt=""></a>
                        {{ Form::open(array('route' => array('department.destroy', $dept->id), 'style' => 'display: inline-block;', 'method' => 'delete', 'onclick' => "if(!confirm('Are you sure to delete?'))return false;")) }}
                        <button type="submit" class="smallButton" style="margin: 5px;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/cross.png') }}}" alt=""></button>
                        {{ Form::close() }}                        
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
    
    
</div>
@stop