app/routes.php
<?php
Event::listen('illuminate.query', function ($sql) {
    // var_dump($sql);
});

Route::get('/current_environment', array(
    'as' => 'test.environment',
    'uses' => 'TestController@environment'
));

Route::get('auth/logout', array(
    'as' => 'auth.logout',
    'uses' => 'AuthController@getLogout'
));
Route::get('auth/login', array(
    'as' => 'auth.login',
    'uses' => 'AuthController@getLogin'
));
Route::post('auth/login', array(
    'as' => 'auth.login.post',
    'uses' => 'AuthController@postLogin'
));

Route::group(array(
    'prefix' => 'project_importer'
        ), function () {
    Route::get('/', array(
        'as' => 'project_importer.index',
        'uses' => 'ProjectImporterController@index'
    ));
    Route::get('/sync_data_from_erp', array(
        'as' => 'project_importer.import_to_db',
        'uses' => 'ProjectImporterController@sync_data_from_erp'
    ));
});

Route::group(array('before' => 'auth.apps'), function () {
    Route::any('/', 'DashboardController@index');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('user', 'UserController');
    Route::resource('userlevel', 'UserLevelController');
    Route::resource('department', 'DepartmentController');
    Route::resource('unit', 'UnitController');
    Route::resource('pic', 'PicController');
    Route::resource('resource', 'ResourceController');
    Route::resource('resource_group', 'ResourceGroupController');
    Route::resource('resource_planner', 'ResourcePlannerController');
    Route::resource('resource_monitor', 'ResourceMonitorController');
    Route::resource('resource_manager', 'ResourceManagerController');
    Route::resource('setting', 'SettingController');
    Route::resource('alert_setting', 'AlertSettingsController');
    Route::resource('email_recipient', 'SettingController');
    Route::resource('helpdesk', 'HelpDeskController');
    Route::resource('helpdesk_request', 'HelpDeskRequestController');
    Route::resource('processes', 'ProjectProcessController');
    Route::resource('process_group', 'ProcessGroupController');
    Route::resource('template_master_plan', 'TemplateMasterPlanController');
    Route::resource('template_mfg_process', 'TemplateMfgProcessController');
    Route::resource('work_time_template', 'ResourceWorkTimeTemplateController');
    Route::resource('menu', 'MenuController');
    Route::resource('exception_days', 'ExceptionDaysController');
    // Route::resource('issue_management', 'IssueManagementsController');
    Route::resource('document', 'DocumentManagementsController');

    // Route::group(array('prefix' => 'issue_management'), function () {
    //     Route::get('/sel', array(
    //         'as' => 'issue_management.select',
    //         'uses' => 'iqi@select_project'
    //     ));

    // });

    Route::group(array(
        'prefix' => 'template_master_plan/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_master_plan_detail.index',
            'uses' => 'TemplateMasterPlanDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_master_plan_detail.create',
            'uses' => 'TemplateMasterPlanDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_master_plan_detail.create.child',
            'uses' => 'TemplateMasterPlanDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_master_plan_detail.store',
            'uses' => 'TemplateMasterPlanDetailController@store'
        ));
        Route::post('/{header_id}/{detail_id}/store', array(
            'as' => 'template_master_plan_detail.store.child',
            'uses' => 'TemplateMasterPlanDetailController@store_child'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_master_plan_detail.edit',
            'uses' => 'TemplateMasterPlanDetailController@edit'
        ));
        Route::post('/{detail_id}/update', array(
            'as' => 'template_master_plan_detail.update',
            'uses' => 'TemplateMasterPlanDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_master_plan_detail.destroy',
            'uses' => 'TemplateMasterPlanDetailController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'template_mfg_process/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_mfg_process_detail.index',
            'uses' => 'TemplateMfgProcessDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_mfg_process_detail.create',
            'uses' => 'TemplateMfgProcessDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_mfg_process_detail.create.child',
            'uses' => 'TemplateMfgProcessDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_mfg_process_detail.store',
            'uses' => 'TemplateMfgProcessDetailController@store'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_mfg_process_detail.edit',
            'uses' => 'TemplateMfgProcessDetailController@edit'
        ));
        Route::put('/{detail_id}/update', array(
            'as' => 'template_mfg_process_detail.update',
            'uses' => 'TemplateMfgProcessDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_mfg_process_detail.destroy',
            'uses' => 'TemplateMfgProcessDetailController@destroy'
        ));
    });

    Route::get('template_mfg_process/excel/import', array(
        'as' => 'template_mfg_process.excel.import',
        'uses' => 'TemplateMfgProcessController@import_excel'
    ));

    Route::post('template_mfg_process/excel/do_import', array(
        'as' => 'template_mfg_process.excel.do_import',
        'uses' => 'TemplateMfgProcessController@do_import_excel'
    ));

    Route::get('/', array(
        'as' => 'dashboard.index',
        'uses' => 'DashboardController@index'
    ));

    Route::get('resource/{id}/set_offline', array(
        'as' => 'resource_manager.set_offline',
        'uses' => 'ResourceManagerController@offline'
    ));

    Route::get('resource_planner/{year}/update', array(
        'as' => 'resource_planner.update.by_year',
        'uses' => 'ResourcePlannerController@create'
    ));

    Route::get('resource_planner/{year}/index', array(
        'as' => 'resource_planner.by_year',
        'uses' => 'ResourcePlannerController@index'
    ));

    Route::get('resource_planner/{resourceid}/{month}/{year}/work_plan', array(
        'as' => 'resource_planner.work_plan',
        'uses' => 'ResourcePlannerController@work_plan_per_month'
    ));

    Route::post('resource_planner/update_work_time_plan', array(
        'as' => 'resource_planner.update_work_time_plan',
        'uses' => 'ResourcePlannerController@update_work_time_plan'
    ));

    Route::post('helpdesk/{requestid}/add_note', array(
        'as' => 'helpdesk.add_note',
        'uses' => 'HelpDeskController@add_note'
    ));

    Route::post('helpdesk_request/{requestid}/update_status', array(
        'as' => 'helpdesk_request.update_status',
        'uses' => 'HelpDeskRequestController@update_status'
    ));

    Route::post('helpdesk_request/{requestid}/add_note', array(
        'as' => 'helpdesk_request.add_note',
        'uses' => 'HelpDeskRequestController@add_note'
    ));

    Route::group(array(
        'prefix' => 'resource_specification'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_spec.index',
            'uses' => 'ResourceSpecificationController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_spec.create',
            'uses' => 'ResourceSpecificationController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_spec.store',
            'uses' => 'ResourceSpecificationController@store'
        ));
        Route::get('/{resourceid}/{id}/show', array(
            'as' => 'resource_spec.show',
            'uses' => 'ResourceSpecificationController@show'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_spec.edit',
            'uses' => 'ResourceSpecificationController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_spec.update',
            'uses' => 'ResourceSpecificationController@update'
        ));
        Route::post('/{resourceid}/{id}/destroy', array(
            'as' => 'resource_spec.destroy',
            'uses' => 'ResourceSpecificationController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'resource_work_time'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_work_time.index',
            'uses' => 'ResourceWorkTimeController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_work_time.create',
            'uses' => 'ResourceWorkTimeController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_work_time.store',
            'uses' => 'ResourceWorkTimeController@store'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_work_time.edit',
            'uses' => 'ResourceWorkTimeController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_work_time.update',

app/models/Pic.php
<?php

class Pic extends Eloquent
{

    protected $table = 'master_pic';

    public static function getPICFullname($id)
    {
        $user = self::find($id);

        return @$user->first_name . ' ' . @$user->last_name;
    }

    public static function getPICs()
    {
        return self::get();
    }

    public static function getSinglePIC($id)
    {
        return self::find($id);
    }
}

app/controllers/PicController.php
<?php
use Pic;
use Unit;
// // use Auth, BaseController, Form, Input, Redirect, Sentry, View, Notification;
use Department;

class PicController extends BaseController
{

    public function __construct()
    {
        View::composer(Config::get('app.theme').'._layouts.master', function ($view)
        {
            $view->with('parent_active', 'user_management');
            $view->with('child_active', 'pic');
        });
    }

    public function index()
    {
        $view = View::make(Config::get('app.theme').'.pic.list');
        $view->with('page_title', 'PIC Management');
        $view->with('sub_title', 'You can manage Resource/Work Center PIC with this page');
        $view->with('theme', Config::get('app.theme'));
        $view->with('pic_lists', Pic::getPICs());

        return $view;
    }

    public function create()
    {
        $view = View::make(Config::get('app.theme').'.pic.create');
        $view->with('page_title', 'PIC Management');
        $view->with('sub_title', 'Create new PIC');
        $view->with('theme', Config::get('app.theme'));
        $view->with('departments', Department::all());
        $view->with('units', Unit::all());

        return $view;
    }

    public function store()
    {
        $pic = new Pic();
        $pic->user_id = Input::get('userid');
        $pic->code = Input::get('code');
        $pic->first_name = Input::get('firstname');
        $pic->last_name = Input::get('lastname');
        $pic->dept_id = Input::get('department');
        $pic->unit_id = Input::get('unit');
        $pic->sex = Input::get('gender');

        if($pic->save())
            Notification::success('New PIC was saved.');

        return Redirect::route('pic.index');
    }

    public function edit($id)
    {
        $view = View::make(Config::get('app.theme').'.pic.edit');
        $view->with('page_title', 'PIC Management');
        $view->with('sub_title', 'Edit PIC ' . Pic::getPICFullname($id));
        $view->with('theme', Config::get('app.theme'));
        $view->with('pic', Pic::find($id));
        $view->with('departments', Department::all());
        $view->with('units', Unit::all());

        return $view;
    }

    public function update($id)
    {
        $pic = Pic::find($id);

        $pic->user_id = Input::get('userid');
        $pic->code = Input::get('code');
        $pic->first_name = Input::get('firstname');
        $pic->last_name = Input::get('lastname');
        $pic->dept_id = Input::get('department');
        $pic->unit_id = Input::get('unit');
        $pic->sex = Input::get('gender');

        if($pic->save())
            Notification::success('PIC data changes was saved.');

        return Redirect::route('pic.index', $id);
    }

    public function destroy($id)
    {
        $pic = Pic::find($id);
        $pic->delete();

        return Redirect::route('pic.index');
    }
}

app/views/default/pic/create.blade.php
@extends($theme . '._layouts.master')
 
@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="wrapper">
    
    <!-- Note -->
    {{ Notification::showAll() }}
    
    <!-- Validation form -->
    {{ Form::open(array('route' => 'pic.store', 'class' => 'form', 'id' => 'validate')) }}
    	<fieldset>
            <div class="widget">
                <div class="title">
                    <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/alert.png') }}}" alt="" class="titleIcon" />
                    <h6>PIC Details</h6>
                </div>
                <div class="formRow">
                    <label>Username:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="userid" id="userid" class="validate[required]">
                                <option value="">Choose Username</option>
                                @foreach (Sentry::findAllUsers() as $user)
                                <option value="{{{ $user->id }}}">{{{ $user->username }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Code:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="code" id="code" value=""/></div><div class="clear"></div>
                </div>                
                <div class="formRow">
                    <label>First Name:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="firstname" id="firstname" value=""/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Last Name:</label>
                    <div class="formRight"><input type="text" name="lastname" id="lastname" value=""/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Gender:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="gender" id="gender" class="validate[required]">
                                <option value="m">Male</option>
                                <option value="f">Female</option>
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Department:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="department" id="department" class="validate[required]">
                                <option value=""></option>
                                @foreach ($departments as $dept)
                                <option value="{{{ $dept->id }}}">{{{ $dept->name }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Unit:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="unit" id="unit" class="validate[required]">
                                <option value=""></option>
                                @foreach ($units as $unit)
                                <option value="{{{ $unit->id }}}">{{{ $unit->name }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                
            </div>
            <div class="formSubmit"><input type="submit" value="Add New PIC" class="redB" /></div>
            <div class="clear"></div>
        </fieldset>
        
    	
    {{ Form::close() }}        
    
</div>
@stop

app/views/default/pic/edit.blade.php
@extends($theme . '._layouts.master')
 
@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="wrapper">
    
    <!-- Note -->
    {{ Notification::showAll() }}
    
    <!-- Validation form -->
    {{ Form::model($pic, array('method' => 'put', 'class' => 'form', 'id' => 'validate', 'route' => array('pic.update', $pic->id))) }}
    	<fieldset>
            <div class="widget">
                <div class="title">
                    <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/alert.png') }}}" alt="" class="titleIcon" />
                    <h6>PIC Details</h6>
                </div>
                <div class="formRow">
                    <label>Username:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="userid" id="userid" class="validate[required]">
                                <option value="">Choose Username</option>
                                @foreach (Sentry::findAllUsers() as $user)
                                <option {{{ $pic->user_id == $user->id ? 'selected' : '' }}} value="{{{ $user->id }}}">{{{ $user->username }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Code:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="code" id="code" value="{{{ $pic->code }}}"/></div><div class="clear"></div>
                </div>                
                <div class="formRow">
                    <label>First Name:<span class="req">*</span></label>
                    <div class="formRight"><input type="text" class="validate[required]" name="firstname" id="firstname" value="{{{ $pic->first_name }}}"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Last Name:</label>
                    <div class="formRight"><input type="text" name="lastname" id="lastname" value="{{{ $pic->last_name }}}"/></div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Gender:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="gender" id="gender" class="validate[required]">
                                <option {{{ $pic->sex == 'm' ? 'selected' : '' }}} value="m">Male</option>
                                <option {{{ $pic->sex == 'f' ? 'selected' : '' }}} value="f">Female</option>
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Department:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="department" id="department" class="validate[required]">
                                <option value=""></option>
                                @foreach ($departments as $dept)
                                <option {{{ $pic->dept_id == $dept->id ? 'selected' : '' }}} value="{{{ $dept->id }}}">{{{ $dept->name }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                <div class="formRow">
                    <label>Unit:<span class="req">*</span></label>
                    <div class="formRight">
                        <div class="floatL">
                            <select name="unit" id="unit" class="validate[required]">
                                <option value=""></option>
                                @foreach ($units as $unit)
                                <option {{{ $pic->unit_id == $unit->id ? 'selected' : '' }}} value="{{{ $unit->id }}}">{{{ $unit->name }}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div><div class="clear"></div>
                </div>
                
            </div>
            <div class="formSubmit"><input type="submit" value="Edit PIC" class="redB" /></div>
            <div class="clear"></div>
        </fieldset>
        
    	
    {{ Form::close() }}        
    
</div>
@stop

app/views/default/pic/list.blade.php
@extends($theme . '._layouts.master')

@section('main')
@include($theme.'._partials.breadcrumb')

<div class="titleArea">
    <div class="wrapper">
        <div class="pageTitle">
            <h5>{{{ $page_title }}}</h5>
            <span>{{{ $sub_title }}}</span>
        </div>
        <div class="clear"></div>
    </div>
</div>
<div class="line"></div>
<div class="statsRow">
    <div class="wrapper">
    	<div class="controlB">
        	<ul>
                <li><a href="{{{ route('department.index') }}}" title="Manage departments"><img src="<?php echo asset('assets/'.$theme.'/images/icons/control/32/suppliers.png') ?>" alt=""><span>Departments</span></a></li>
                <li><a href="{{{ route('unit.index') }}}" title="Manage units"><img src="<?php echo asset('assets/'.$theme.'/images/icons/control/32/order.png') ?>" alt=""><span>Units</span></a></li>
            </ul>
            <div class="clear"></div>
        </div>
    </div>
</div>
<div class="line"></div>
<!-- Main content wrapper -->
<div class="wrapper">
    {{ Notification::showAll() }}

    <!-- Static table -->
    <div class="widget">
      <div class="title">
        <img src="{{{ asset('assets/'.$theme.'/images/icons/dark/frames.png') }}}" alt="" class="titleIcon" />
        <h6>User Lists</h6>
        <a href="{{{ route('pic.create') }}}" title="Add User" class="button greenB" style="margin: 4px; float: right;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/plus.png') }}}" alt="Add User" class="icon" style="margin-top: 5px; margin-left: 5px;"><span>Add New PIC</span></a>
      </div>
        <table cellpadding="0" cellspacing="0" width="100%" class="sTable">
            <thead>
                <tr>
                    <td>Code</td>
                    <td>Username</td>
                    <td>Fullname</td>
                    <td>Department</td>
                    <td>Unit</td>
                    <td width="11%">Action</td>
                </tr>
            </thead>
            <tbody>
                @foreach ($pic_lists as $pic)
                <tr>
                    <td align="center">{{{ $pic->code }}}</td>
                    <td align="center">{{{ UserInformation::getUserName($pic->user_id) }}}</td>
                    <td>{{{ ucwords($pic->first_name . ' ' . $pic->last_name) }}}</td>
                    <td align="center">{{{ Department::getName($pic->dept_id) }}}</td>
                    <td align="center">{{{ Unit::getName($pic->unit_id) }}}</td>
                    <td align="center">
                        <a href="{{{ route('pic.edit', $pic->id) }}}" title="Edit" class="smallButton tipN" style="margin: 5px;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/pencil.png') }}}" alt=""></a>
                        {{ Form::open(array('route' => array('pic.destroy', $pic->id), 'style' => 'display: inline-block;', 'method' => 'delete', 'onclick' => "if(!confirm('Are you sure to delete?'))return false;")) }}
                        <button type="submit" class="smallButton tipN" title="Delete" style="margin: 5px;"><img src="{{{ asset('assets/'.$theme.'/images/icons/color/cross.png') }}}" alt=""></button>
                        {{ Form::close() }}
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>


</div>
@stop