app/routes.php
<?php
Event::listen('illuminate.query', function ($sql) {
    // var_dump($sql);
});

Route::get('/current_environment', array(
    'as' => 'test.environment',
    'uses' => 'TestController@environment'
));

Route::get('auth/logout', array(
    'as' => 'auth.logout',
    'uses' => 'AuthController@getLogout'
));
Route::get('auth/login', array(
    'as' => 'auth.login',
    'uses' => 'AuthController@getLogin'
));
Route::post('auth/login', array(
    'as' => 'auth.login.post',
    'uses' => 'AuthController@postLogin'
));

Route::group(array(
    'prefix' => 'project_importer'
        ), function () {
    Route::get('/', array(
        'as' => 'project_importer.index',
        'uses' => 'ProjectImporterController@index'
    ));
    Route::get('/sync_data_from_erp', array(
        'as' => 'project_importer.import_to_db',
        'uses' => 'ProjectImporterController@sync_data_from_erp'
    ));
});

Route::group(array('before' => 'auth.apps'), function () {
    Route::any('/', 'DashboardController@index');
    Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

    Route::resource('user', 'UserController');
    Route::resource('userlevel', 'UserLevelController');
    Route::resource('department', 'DepartmentController');
    Route::resource('unit', 'UnitController');
    Route::resource('pic', 'PicController');
    Route::resource('resource', 'ResourceController');
    Route::resource('resource_group', 'ResourceGroupController');
    Route::resource('resource_planner', 'ResourcePlannerController');
    Route::resource('resource_monitor', 'ResourceMonitorController');
    Route::resource('resource_manager', 'ResourceManagerController');
    Route::resource('setting', 'SettingController');
    Route::resource('alert_setting', 'AlertSettingsController');
    Route::resource('email_recipient', 'SettingController');
    Route::resource('helpdesk', 'HelpDeskController');
    Route::resource('helpdesk_request', 'HelpDeskRequestController');
    Route::resource('processes', 'ProjectProcessController');
    Route::resource('process_group', 'ProcessGroupController');
    Route::resource('template_master_plan', 'TemplateMasterPlanController');
    Route::resource('template_mfg_process', 'TemplateMfgProcessController');
    Route::resource('work_time_template', 'ResourceWorkTimeTemplateController');
    Route::resource('menu', 'MenuController');
    Route::resource('exception_days', 'ExceptionDaysController');
    // Route::resource('issue_management', 'IssueManagementsController');
    Route::resource('document', 'DocumentManagementsController');

    // Route::group(array('prefix' => 'issue_management'), function () {
    //     Route::get('/sel', array(
    //         'as' => 'issue_management.select',
    //         'uses' => 'iqi@select_project'
    //     ));

    // });

    Route::group(array(
        'prefix' => 'template_master_plan/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_master_plan_detail.index',
            'uses' => 'TemplateMasterPlanDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_master_plan_detail.create',
            'uses' => 'TemplateMasterPlanDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_master_plan_detail.create.child',
            'uses' => 'TemplateMasterPlanDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_master_plan_detail.store',
            'uses' => 'TemplateMasterPlanDetailController@store'
        ));
        Route::post('/{header_id}/{detail_id}/store', array(
            'as' => 'template_master_plan_detail.store.child',
            'uses' => 'TemplateMasterPlanDetailController@store_child'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_master_plan_detail.edit',
            'uses' => 'TemplateMasterPlanDetailController@edit'
        ));
        Route::post('/{detail_id}/update', array(
            'as' => 'template_master_plan_detail.update',
            'uses' => 'TemplateMasterPlanDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_master_plan_detail.destroy',
            'uses' => 'TemplateMasterPlanDetailController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'template_mfg_process/detail'
            ), function () {
        Route::get('/{header_id}/index', array(
            'as' => 'template_mfg_process_detail.index',
            'uses' => 'TemplateMfgProcessDetailController@index'
        ));
        Route::get('/{header_id}/create', array(
            'as' => 'template_mfg_process_detail.create',
            'uses' => 'TemplateMfgProcessDetailController@create'
        ));
        Route::get('/{header_id}/{detail_id}/create/child', array(
            'as' => 'template_mfg_process_detail.create.child',
            'uses' => 'TemplateMfgProcessDetailController@create_child'
        ));
        Route::post('/{header_id}/store', array(
            'as' => 'template_mfg_process_detail.store',
            'uses' => 'TemplateMfgProcessDetailController@store'
        ));
        Route::get('/{detail_id}/edit', array(
            'as' => 'template_mfg_process_detail.edit',
            'uses' => 'TemplateMfgProcessDetailController@edit'
        ));
        Route::put('/{detail_id}/update', array(
            'as' => 'template_mfg_process_detail.update',
            'uses' => 'TemplateMfgProcessDetailController@update'
        ));
        Route::delete('/{detail_id}/destroy', array(
            'as' => 'template_mfg_process_detail.destroy',
            'uses' => 'TemplateMfgProcessDetailController@destroy'
        ));
    });

    Route::get('template_mfg_process/excel/import', array(
        'as' => 'template_mfg_process.excel.import',
        'uses' => 'TemplateMfgProcessController@import_excel'
    ));

    Route::post('template_mfg_process/excel/do_import', array(
        'as' => 'template_mfg_process.excel.do_import',
        'uses' => 'TemplateMfgProcessController@do_import_excel'
    ));

    Route::get('/', array(
        'as' => 'dashboard.index',
        'uses' => 'DashboardController@index'
    ));

    Route::get('resource/{id}/set_offline', array(
        'as' => 'resource_manager.set_offline',
        'uses' => 'ResourceManagerController@offline'
    ));

    Route::get('resource_planner/{year}/update', array(
        'as' => 'resource_planner.update.by_year',
        'uses' => 'ResourcePlannerController@create'
    ));

    Route::get('resource_planner/{year}/index', array(
        'as' => 'resource_planner.by_year',
        'uses' => 'ResourcePlannerController@index'
    ));

    Route::get('resource_planner/{resourceid}/{month}/{year}/work_plan', array(
        'as' => 'resource_planner.work_plan',
        'uses' => 'ResourcePlannerController@work_plan_per_month'
    ));

    Route::post('resource_planner/update_work_time_plan', array(
        'as' => 'resource_planner.update_work_time_plan',
        'uses' => 'ResourcePlannerController@update_work_time_plan'
    ));

    Route::post('helpdesk/{requestid}/add_note', array(
        'as' => 'helpdesk.add_note',
        'uses' => 'HelpDeskController@add_note'
    ));

    Route::post('helpdesk_request/{requestid}/update_status', array(
        'as' => 'helpdesk_request.update_status',
        'uses' => 'HelpDeskRequestController@update_status'
    ));

    Route::post('helpdesk_request/{requestid}/add_note', array(
        'as' => 'helpdesk_request.add_note',
        'uses' => 'HelpDeskRequestController@add_note'
    ));

    Route::group(array(
        'prefix' => 'resource_specification'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_spec.index',
            'uses' => 'ResourceSpecificationController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_spec.create',
            'uses' => 'ResourceSpecificationController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_spec.store',
            'uses' => 'ResourceSpecificationController@store'
        ));
        Route::get('/{resourceid}/{id}/show', array(
            'as' => 'resource_spec.show',
            'uses' => 'ResourceSpecificationController@show'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_spec.edit',
            'uses' => 'ResourceSpecificationController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_spec.update',
            'uses' => 'ResourceSpecificationController@update'
        ));
        Route::post('/{resourceid}/{id}/destroy', array(
            'as' => 'resource_spec.destroy',
            'uses' => 'ResourceSpecificationController@destroy'
        ));
    });

    Route::group(array(
        'prefix' => 'resource_work_time'
            ), function () {
        Route::get('/{resourceid}', array(
            'as' => 'resource_work_time.index',
            'uses' => 'ResourceWorkTimeController@index'
        ));
        Route::get('/{resourceid}/create', array(
            'as' => 'resource_work_time.create',
            'uses' => 'ResourceWorkTimeController@create'
        ));
        Route::post('/{resourceid}/store', array(
            'as' => 'resource_work_time.store',
            'uses' => 'ResourceWorkTimeController@store'
        ));
        Route::get('/{resourceid}/{id}/edit', array(
            'as' => 'resource_work_time.edit',
            'uses' => 'ResourceWorkTimeController@edit'
        ));
        Route::post('/{resourceid}/{id}/update', array(
            'as' => 'resource_work_time.update',

app/controllers/ResourceManagerController.php
<?php

class ResourceManagerController extends BaseController
{

    public function __construct()
    {
        View::composer(Config::get('app.theme').'._layouts.master', function ($view)
        {
            $view->with('parent_active', 'resource_center');
            $view->with('child_active', 'resource_manager');
        });
    }

    public function index()
    {
        $view = View::make(Config::get('app.theme').'.resource_manager.list');
        $view->with('page_title', 'Resource Manager');
        $view->with('sub_title', 'Start and/or stop resources');
        $view->with('theme', Config::get('app.theme'));
        $view->with('in_plan_resources', Resource::where('plan_type', '=', 'in plan')->get());
        $view->with('out_plan_resources', Resource::where('plan_type', '=', 'out plan')->get());
        $view->with('breadcrumb', array(
            'Dashboard' => array(route('dashboard.index')),
            'Resource Manager' => array(route('resource_manager.index'), 'last')
        ));

        return $view;
    }

    public function offline($id)
    {
        $resource = Resource::find($id);

        if ($resource->is_offline == '1') {
            $resource->is_offline = '0';
            $resource->start_date = date('Y-m-d H:i:s', time());
            $message = 'Resource is set to ONLINE.';
        } else {
            $resource->is_offline = '1';
            $resource->stop_date = date('Y-m-d H:i:s', time());
            $message = 'Resource is set to OFFLINE.';
        }

        $resource->save();

        Notification::success($message);

        return Redirect::route('resource_manager.index');
    }
}

/**
 * End of file
 *
 */

app/views/adminre/resource_manager/detail.blade.php
@extends($theme.'._layouts.master')

@section('additional_css')
<link rel="stylesheet" href="{{{ asset('assets/'.$theme.'/plugins/xeditable/css/bootstrap-editable.min.css') }}}">
<link rel="stylesheet" href="{{{ asset('assets/'.$theme.'/plugins/xeditable/inputs-ext/typeaheadjs/lib/typeahead.js-bootstrap.css') }}}">
<link rel="stylesheet" href="{{{ asset('assets/'.$theme.'/plugins/gritter/css/jquery.gritter.min.css') }}}">
<link rel="stylesheet" href="{{{ asset('assets/'.$theme.'/plugins/datatables/css/jquery.datatables.min.css') }}}">
<link rel="stylesheet" href="{{{ asset('assets/'.$theme.'/plugins/gritter/css/jquery.gritter.min.css') }}}">
<style type="text/css">
.dataTables_length{ float: left }
.DTTT{ float: left; }
.toolbar_search{ float: right; margin-right: 0px; }
</style>
@stop

@section('main')
<section id="main" role="main">
    <!-- START Template Container -->
    <div class="container-fluid">
        <!-- Page Header -->
        <div class="page-header page-header-block">
            <div class="page-header-section">
                <h4 class="title semibold">{{{ $page_title }}}</h4>
            </div>
            <div class="page-header-section">
                <!-- Toolbar -->
                <div class="toolbar">
                    <ol class="breadcrumb breadcrumb-transparent nm">
                        <li><a href="{{{ route('dashboard.index') }}}">Dashboard</a></li>
                        <li><a href="{{{ route('resource_monitor.index') }}}">Resource Monitor</a></li>
                        <li class="active">Resource Monitor Details</li>
                    </ol>
                </div>
                <!--/ Toolbar -->
            </div>
        </div>
        <!-- Page Header -->

        <div class="row">
            <div class="col-md-12">
                {{ Notification::showAll() }}

                <!-- START panel -->
                <div class="panel panel-primary">
                    <!-- panel heading/header -->
                    <div class="panel-heading">
                        <h3 class="panel-title"><span class="panel-icon mr5"><i class="ico-table22"></i></span>Resource Monitoring Details</h3>
                        <!-- panel toolbar -->
                        <div class="panel-toolbar text-right">
                            <!-- option -->
                            <div class="option">
                                <button class="btn up" data-toggle="panelcollapse"><i class="arrow"></i></button>
                                <button class="btn" data-toggle="panelremove" data-parent=".col-md-12"><i class="remove"></i></button>
                            </div>
                            <!--/ option -->
                        </div>
                        <!--/ panel toolbar -->
                    </div>
                    <!--/ panel heading/header -->

                    <!-- panel body with collapse capabale -->
                    <div class="table-responsive panel-collapse pull out">
                        <table class="table table-striped table-bordered table-hover" id="resources-table">
                            <thead>
                                <tr>
                                    <th class="text-center">Code</th>
                                    <th class="text-center">Name</th>
                                    <th class="text-center">NOP</th>
                                    <th class="text-center">Process</th>
                                    <th class="text-center">PIC</th>
                                    <th class="text-center">Hours</th>
                                    <th class="text-center">Status</th>
                                </tr>
                            </thead>
                            <tbody style="font-size: 10px;">
                                @foreach ($details as $detail)
                                @if(@$detail->planning->masterplan->project['nop'] && @$detail->status != 'COMPLETE')
                                 {{-- && isset($detail->pic->first_name)) --}}
                                <tr>
                                    <td class="text-center">{{{ $resource->code }}}</td>
                                    <td class="text-left">{{{ strtoupper($resource->name) }}}</td>
                                    <td class="text-center">{{{ $detail->planning->masterplan->project['nop'] }}}</td>
                                    <td class="text-center">{{{ $detail->planning->process->process }}}</td>
                                    <td class="text-center">{{{ @$detail->pic->first_name.' '.@$detail->pic->last_name }}}</td>
                                    <td class="text-center">{{{ round((time() - strtotime($detail->start_date)) / 3600, 2) }}}</td>
                                    <td class="text-center">{{{ $detail->status }}}</td>
                                </tr>
                                @endif
                                @endforeach
                            </tbody>
                        </table>

                    </div>

                    <!--/ panel body with collapse capabale -->
                </div>
            </div>
        </div>
    </div>
    <!--/ END Template Container -->

    <!-- START To Top Scroller -->
    <a href="#" class="totop animation" data-toggle="waypoints totop" data-showanim="bounceIn" data-hideanim="bounceOut" data-offset="50%"><i class="ico-angle-up"></i></a>
    <!--/ END To Top Scroller -->

</section>
@stop

@section('additional_scripts')
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/sparkline/js/jquery.sparkline.min.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/datatables/js/jquery.datatables.min.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/datatables/tabletools/js/tabletools.min.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/datatables/tabletools/js/zeroclipboard.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/datatables/js/jquery.datatables-custom.min.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/gritter/js/jquery.gritter.min.js') }}}"></script>
<script type="text/javascript" src="{{{ asset('assets/'.$theme.'/plugins/bootbox/js/bootbox.min.js') }}}"></script>
<script type="text/javascript">
function deleteItem(elem) {
    var self = $(elem);
    bootbox.confirm("Are you sure to delete this resource?", function (result) {
        if(result){
            var resourceid = self.data('id');
            $('button#del-'+resourceid).click();
        }
    });
}
(function(){
    var table = $("#resources-table").dataTable({
        "sDom": "<'row'<'col-sm-6'Tl><'col-sm-6'f>><'table-responsive'rt><'row'<'col-sm-6'p><'col-sm-6'i>>",
        "oTableTools": {
            "sSwfPath": "{{{ asset('assets/'.$theme.'/plugins/datatables/tabletools/swf/copy_csv_xls_pdf.swf') }}}",
            "aButtons": [
                "print",
                "pdf",
                "csv"
            ]
        },
        "aoColumns": [
            { "sClass": "text-center" },
            { "sClass": "text-left" },
            { "sClass": "text-left" },
            { "sClass": "text-left" },
            { "sClass": "text-left" },
            { "sClass": "text-left" },
            { "sClass": "text-left" }
        ],
        "iDisplayLength": 10
    });
})();
</script>
<!-- <script type="text/javascript" src="{{{ asset('assets/'.$theme.'/javascript/components/notification.js') }}}"></script> -->
@stop